title: Manager en réseau
baseURL: /
params:
  footer:
    content: '&copy; All rights reserved.'
    links:
      - new_window: true
        text: Made with Stackbit
        url: 'https://www.stackbit.com'
  header:
    bg: light
    has_nav: true
    has_social: true
    profile_img: /images/photomaton titi.jpg
    tagline: L'art de manager et coopérer en transverse
    title: 'Manager et coopérer en réseau '
  layout_style: default
  palette: orange
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
